### ISSUE TITLE
SGPS fracpol

### ISSUE THREAD

**Issue by jackieykma** [CIRADA-Tools/RMTable#1]
Hi Cameron,

I have taken a quick look into the RMTable (only sources from SGPS, Taylor+ 2009, and SPASS/ATCA)

I noticed that for the SGPS data, the fracpol appears to be in per-cent instead of fraction (which would follow the convention defined in the Google Doc).

Could you please check if it is indeed the case?

Thanks,
Jackie

Edit: Seems to be the case for CGPS2003 as well; all other entries seem fine

**Comment by Cameron-Van-Eck** [comment]
Yep, looks like I forgot to make that conversion. Also for the new CGPS RMs (which aren't in the catalog yet, but uses the same convention).

Thanks a lot for finding this! There's probably a lot of little mistakes like this; it's hard to keep track of everything when dealing with a few dozen catalogs. I really appreciate you taking the time to look at the master catalog and reporting things like this.

I'm currently drowning in pipeline work, so I'm not going to generate a fixed version right away, but I'll leave the issue open as a reminder to do it when I get back to working on this again.

**Comment by jackieykma** [comment]
No problem, glad that I could help! I have to say that this RM catalogue is really useful and I appreciate your effort in building & maintaining it!

**Comment by Cameron-Van-Eck** [comment]
I forgot to close this issue when I fixed this last year. Whoops. Sorry for the spam.
