### ISSUE TITLE
Verifying UCDs and missing main

### ISSUE THREAD

**Issue by AlecThomson** [CIRADA-Tools/RMTable#6]
Hey @Cameron-Van-Eck,

Just a couple of issues I've encountered when dealing with CASDA - but will likely come up with any other VO client.

We might want to add a UCD verifier method like:

```python
from astropy.io import votable as vot
def verify_ucds(self):
    for colname, ucd in self.ucds.items():
        check = vot.ucd.check_ucd(ucd)
        if not check:
            warning.warning(f"{colname} has invalid ucd '{ucd}'")
```

There is also a requirement for at least one column to have the UCD `'meta.id;meta.main'`, so I'd suggest we use `cat_id` for this in the `column_standard`:
```
    "cat_id": {
        "dtype": "U40",
        "limits": "",
        "blank": "",
        "units": "",
        "ucd": "meta.id;meta.main",
        "description": "Source ID in catalog"
    },
```

**Comment by Cameron-Van-Eck** [comment]
Sounds good to me. I've implemented those changes.
