### ISSUE TITLE
POGS-I polarisation is incorrect

### ISSUE THREAD

**Issue by AlecThomson** [CIRADA-Tools/RMTable#7]
Hey @Cameron-Van-Eck,

I was diving into why I had bad x-matches with [POGS-I ](https://ui.adsabs.harvard.edu/abs/2018PASA...35...43R/abstract), and I found that the polarisation data recorded in the consolidated catalogue has broken somehow. Here are the first 5 POGS sources in the consolidated catalogue vs how they appear in the POGS paper:
```
>>> pogs[0:5]["cat_id","ra","dec", "stokesI", "polint","fracpol","rm"]
<RMTable length=5>
 cat_id         ra                 dec              stokesI             polint       fracpol         rm        
               deg                 deg                 Jy                 Jy                      rad / m2     
bytes40      float64             float64            float64            float64       float64      float64      
------- ------------------ ------------------- ------------------ ------------------ ------- ------------------
  01-01 3.4223338647083654   -30.1557043865717 0.8100000023841858 21.799999237060547     nan  2.700000047683716
  01-02  5.096011558142791 -20.479404053561446 1.1299999952316284  58.20000076293945     nan  5.199999809265137
  01-03  5.111101501986307  -20.23090405054285  2.190000057220459               39.5     nan 1.7999999523162842
  01-04  5.311521269052576 -19.177204010424283 3.9000000953674316  150.3000030517578     nan 3.9000000953674316
  01-05  9.786292613015133 -24.413703102834504 0.9900000095367432               29.5     nan                3.0
  ```
![image](https://user-images.githubusercontent.com/9074527/180954712-ad255129-0b7e-4b2c-a735-fe75e9eb819c.png)

It looks like the polarisation fraction ('m') has been erroneously entered as the RM!

I wasn't able to quickly track down the source catalogue for POGS-I. Maybe @astroripples can help out here?

**Comment by AstroRipples** [comment]
Ah yes... Alec is right -- `fracpol` and `rm` have indeed been swapped. I also note that `polint` is reported in _mJy_ in our paper, rather than Jy!

**Comment by AlecThomson** [comment]
Hey both,

I've scraped the TeX source and produced this FITS catalogue:
[pogs_rmtab.fits.zip](https://github.com/CIRADA-Tools/RMTable/files/9188339/pogs_rmtab.fits.zip)

It only includes the columns that are in the above table, so there are some missing columns from the full RMTable standard that could be filled in from the paper itself. @Cameron-Van-Eck would you be happy to fill those values in and reintegrate this with the main catalogue?

**Comment by Cameron-Van-Eck** [comment]
Hey guys. This was completely my fault; I botched the read-in of the table. Once I looked at it again, it was very easy to fix that (including fixing the units) and re-run the rest of the code to add all the other columns/metadata. I've done that and integrated the updated version in the consolidated catalog. Thanks for catching this!
