### ISSUE TITLE
Standard conflicts with SQL

### ISSUE THREAD

**Issue by AlecThomson** [CIRADA-Tools/RMTable#8]
Hey @Cameron-Van-Eck,

I've just found out (thanks to @jd-au), that the current standard conflicts with VOTable compliance because of the columns `catalog` and `interval`.  These are reserved words in SQL. I'd suggest we change them to: `catalog_name` and `obs_interval`.

**Comment by Cameron-Van-Eck** [comment]
Thanks for pointing this out. I've made this change (commit [50cd570](https://github.com/CIRADA-Tools/RMTable/commit/50cd5706bb9bfb85fe381e6d71f4335007e03e02)) and updated the paper (and mentioned in my reply-to-referee).
